name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 14.0.1
      run: sudo xcode-select -switch /Applications/Xcode_14.0.1.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
